services:
  - type: web
    name: finance-tracker-backend
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/finance-tracker-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
